# GitHub Sponsors configuration
# Note: GitHub Sponsors enrollment required to enable sponsorship
# To enable: Apply at https://github.com/sponsors

# github: jeremylongshore  # Uncomment after GitHub Sponsors enrollment

# Active funding platforms
buy_me_a_coffee: jeremylongshore

# Optional: Add other funding platforms when available
# ko_fi: jeremylongshore
# patreon: jeremylongshore

# Community support and discussions
custom:
  - "https://github.com/jeremylongshore/claude-code-plugins/discussions"
