# Support this project
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors (Preferred - supports tier system)
github: jeremylongshore

# Buy Me a Coffee (One-time donations)
buy_me_a_coffee: jeremylongshore

# Additional sponsor links
custom:
  - "https://stokedautomations.com/sponsor"
  - "https://github.com/AndroidNextdoor/stoked-automations/discussions"
